### ISSUE TITLE
Error "Failed to find where HEAD diverged from main. Does main exist?"

### ISSUE THREAD

**Issue by synulux** [caffco/changed-packages-github-action#758]
I'm getting this error when calling this action, here's my workflow file with the relevant information:
```yaml
name: Add Dependabot changeset

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  add-changeset:
    name: Add changeset
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Get changed packages
        id: changes
        uses: caffco/changed-packages-github-action@v0.0.8

      - name: Show changed packages
        run: echo ${{ steps.changes.outputs.changed_packages }}
```

And this is what I get in the workflow output:
![image](https://github.com/caffco/changed-packages-github-action/assets/133937431/ad0efdaf-1174-44f6-ab35-46755291674d)

Then main branch **does** exist in my repository, and `changesets` is also configured; unsure what's causing this issue... 😭
